--
-- File generated with SQLiteStudio v3.4.21 on Fri Feb 20 15:28:11 2026
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: PICTURE
DROP TABLE IF EXISTS PICTURE;
CREATE TABLE PICTURE (ID INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT NOT NULL, PATH TEXT NOT NULL UNIQUE, FLAGS INTEGER NOT NULL);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
